/**
 * 
 */
package Presentacion.Comandos;

/** 
 * <!-- begin-UML-doc -->
 * <!-- end-UML-doc -->
 * @author Alex
 * @generated "UML a JPA (com.ibm.xtools.transform.uml2.ejb3.java.jpa.internal.UML2JPATransform)"
 */
public enum IdEventos {

	ERROR_ALTA_ALUMNO,
	ERROR_ALTA_ASIGNATURA,
	ERROR_ALTA_GRUPO,
	ERROR_BAJA_ASIGNATURA,
	ERROR_BAJA_ALUMNO,
	ERROR_BAJA_GRUPO,
	ERROR_CONSULTAR_ASIGNATURA,
	ERROR_CONSULTAR_ALUMNO,
	ERROR_CONSULTAR_GRUPO,
	ERROR_CONSULTAR_TODOS_ALUMNOS,
	ERROR_MODIFICAR_ALUMNO,
	ERROR_MODIFICAR_ASIGNATURA,
	ERROR_MODIFICAR_GRUPO,
	EVENTO_ALTA_ALUMNO,
	EVENTO_ALTA_ASIGNATURA,
	EVENTO_ALTA_GRUPO,
	EVENTO_BAJA_ALUMNO,
	EVENTO_BAJA_ASIGNATURA,
	EVENTO_BAJA_GRUPO,
	EVENTO_CONSULTAR_ALUMNO,
	EVENTO_CONSULTAR_ASIGNATURA,
	EVENTO_CONSULTAR_GRUPO,
	EVENTO_CONSULTAR_TODOS_ALUMNOS,
	EVENTO_MODIFICAR_ALUMNO, EVENTO_CONSULTAR_ALUMNO_V_MODIFICAR,
	ERROR_CONSULTAR_ALUMNO_V_MODIFICAR, ERROR_CONSULTAR_ALUMNO_V_BORRAR, 
	EVENTO_CONSULTAR_ALUMNO_V_BORRAR, EVENTO_CONSULTAR_TODOS_ALUMNO, 
	ERROR_CONSULTAR_TODOS_ALUMNO, EVENTO_CONSULTAR_ASIGNATURA_V_BORRAR, 
	ERROR_CONSULTAR_ASIGNATURA_V_BORRAR, EVENTO_CONSULTAR_GRUPO_V_BORRAR, ERROR_CONSULTAR_GRUPO_V_BORRAR,
}